all:
  hosts:
    node1:
      ansible_host: 116.203.203.175
      ip: 116.203.203.175
      access_ip: 116.203.203.175
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node1:
    etcd:
      hosts:
        node1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
